import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Container from '../components/Container'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NeoG Interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/build-questions" passHref>
            <div className={styles.card}>
              <h2>Build Questions &rarr;</h2>
              <p>Solutions for all the build questions</p>
            </div>
          </Link>
          <Link href="/mock-questions" passHref>
            <div className={styles.card}>
              <h2>Mock Questions &rarr;</h2>
              <p>Solutions for all the build questions</p>
            </div>
          </Link>
          <Link href="/conceptual-questions" passHref>
            <div className={styles.card}>
              <h2>Mock Questions &rarr;</h2>
              <p>Solutions for all the conceptual questions</p>
            </div>
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  )
}
